### ISSUE TITLE
Quick edits on the installation docs

### ISSUE THREAD

**Issue by Peruz** [BenjMy/pycathy_wrapper#26]
Hi Ben,

Thank you for reducing all the dependencies to just blas and lapack, smooth installation.
On Fedora, I think they are `blas-devel` and `lapack-devel` rather than `...-dev`, which is the right one on Ubuntu.

Do you think it is worth highlighting that pyCATHY already includes CATHY, and thus does not require a separate installation of CATHY before using pyCATHY as a wrapper?

Best,
Luca

**Comment by BenjMy** [comment]
Thanks Luca for  spotting this issue! I made the change accordingly and added a sentence to the doc to explain that pyCATHY automatically fetch the CATHY core files.
